CREATE TABLE IF NOT EXISTS recipe (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    servings INT NOT NULL,
    vegetarian BOOLEAN NOT NULL,
    instructions TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `ingredient` (
   id INT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   recipe INT,
   FOREIGN KEY (recipe) REFERENCES recipe(id)
)  ENGINE=INNODB;